[package]
name = "telchar"
version = "0.1.0"
edition = "2024"

[dependencies]
nix-worker-protocol = { path = "../nix-worker-protocol" }
serde.workspace = true
serde_json.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry-appender-tracing.workspace = true
tokio.workspace = true
rustix = { version = "1.1.4", features = [
  "event",
  "fs",
  "net",
  "process",
  "time",
] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
sha2 = "0.10"
base64 = "0.22"

[dev-dependencies]
opentelemetry-proto.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
